version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bamakolimo76
    volumes:
      - thingsboard_pgdata:/var/lib/postgresql/data

  thingsboard:
    image: thingsboard/tb-postgres
    restart: always
    ports:
      - "18080:8080"
    depends_on:
      - postgres
    environment:
      TB_QUEUE_TYPE: in-memory
      DATABASE_TS_TYPE: sql
      DATABASE_TS_SQL_PROVIDER: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Bamakolimo76
      SPRING_PROFILES_ACTIVE: postgres
    volumes:
      - thingsboard_logs:/var/log/thingsboard

volumes:
  thingsboard_pgdata:
  thingsboard_logs:
