version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-thingsboard}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Bamakolimo76}
    volumes:
      - "thingsboard_pgdata:/var/lib/postgresql/data"

  tb-core1:
    image: thingsboard/tb-core:latest
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
    volumes:
      - "thingsboard_logs:/var/log/thingsboard"

  tb-core2:
    image: thingsboard/tb-core:latest 
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
    volumes:
      - "thingsboard_logs:/var/log/thingsboard"

  tb-rule-engine1:
    image: thingsboard/tb-rule-engine:latest
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres

  tb-rule-engine2:
    image: thingsboard/tb-rule-engine:latest
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres

volumes:
  thingsboard_pgdata:
  thingsboard_logs:
